export const ACCOUNT_REGISTER = 'ACCOUNT_REGISTER';
export const ACCOUNT_REQUEST_RESET_PASSWORD = 'ACCOUNT_REQUEST_RESET_PASSWORD';
export const ACCOUNT_CHANGE_PASSWORD = 'ACCOUNT_CHANGE_PASSWORD';
export const ACCOUNT_UPDATE_PROFILE = 'ACCOUNT_UPDATE_PROFILE';
export const ACCOUNT_PROFILE_INFO = 'ACCOUNT_PROFILE_INFO';
export const LOGIN_BY_GOOGLE = 'LOGIN_BY_GOOGLE';
export const COMMON_LOADING = 'COMMON_LOADING';

export const PAYMENT_QUERY_HISTORY = 'PAYMENT_QUERY_HISTORY';
