export const ACCOUNT_REGISTER = 'ACCOUNT_REGISTER';
export const ACCOUNT_REQUEST_RESET_PASSWORD = 'ACCOUNT_REQUEST_RESET_PASSWORD';
export const LOGIN_BY_GOOGLE = 'LOGIN_BY_GOOGLE';
export const COMMON_LOADING = 'COMMON_LOADING';
